export enum WorkflowType {

  STUDENT_REGISTERED = "STUDENT_REGISTERED",

  PAYMENT_INITIALIZED = "PAYMENT_INITIALIZED",

  PAYMENT_SUCCESSFUL = "PAYMENT_SUCCESSFUL",

  PAYMENT_FAILED = "PAYMENT_FAILED",

  AI_LEAD_CAPTURED = "AI_LEAD_CAPTURED",

  AI_COURSE_RECOMMENDATION = "AI_COURSE_RECOMMENDATION",

  LMS_ENROLLMENT = "LMS_ENROLLMENT",

  CERTIFICATE_READY = "CERTIFICATE_READY",

  WELCOME_EMAIL = "WELCOME_EMAIL",

  WHATSAPP_MESSAGE = "WHATSAPP_MESSAGE",

  ADMIN_NOTIFICATION = "ADMIN_NOTIFICATION",

  AI_REGISTER_REQUEST = "AI_REGISTER_REQUEST",

AI_PAYMENT_REQUEST = "AI_PAYMENT_REQUEST",

AI_CONTACT_REQUEST = "AI_CONTACT_REQUEST",

}